### ISSUE TITLE
priorities 3.46

### ISSUE THREAD

**Issue by smanders** [smanders/externpro#134]
### [17.03.1](https://github.com/smanders/externpro/milestone/11?closed=1) ###
- [x] [create header resources via wxInclude](https://github.com/smanders/externpro/issues/123)
- [x] [add propgrid to wx_libs](https://github.com/smanders/externpro/issues/121)
- [x] [remove node.js version 5](https://github.com/smanders/externpro/issues/122)
- [x] [update zlib and gsoap download URLs](https://github.com/smanders/externpro/issues/125)
- [x] [xpSourceListAppend enhancements](https://github.com/smanders/externpro/issues/124)
- [x] [minor find script cleanup](https://github.com/smanders/externpro/issues/126)
- [x] [allow projects that use externpro to set CPACK_PACKAGE_VENDOR](https://github.com/smanders/externpro/issues/127)
- [x] [update boost](https://github.com/smanders/externpro/issues/39)
- [x] [update the cmake version](https://github.com/smanders/externpro/issues/129)

### [17.05.1](https://github.com/smanders/externpro/milestone/12?closed=1) ###
- [x] [mkpatch step needs some serialization to support parallel builds](https://github.com/smanders/externpro/issues/135)
- [x] [XP_CMAKE_REPO_INSYNC enhancements](https://github.com/smanders/externpro/issues/136)
- [x] [remove boost version 1.57.0](https://github.com/smanders/externpro/issues/137)
- [x] [Add web socket c++ library: websocketpp](https://github.com/smanders/externpro/issues/131)
- [x] [add clang-tidy](https://github.com/smanders/externpro/issues/138)

### [next](https://github.com/smanders/externpro/milestone/2) ###
- [ ] [add FFmpeg](https://github.com/smanders/externpro/issues/17)

### 17.04.1 ###
- [x] build against next release of externpro (17.03.1)
- [x] palam built against boost 1.63.0
- [x] GDP undefined references with boost 1.63.0

### 17.05.1 (16.08.7 for GDP) ###
- [x] update GDP 17.05
- [x] remove fx400
- [x] build against next release of externpro (17.05.1)
- [x] remove palam v113 and GDP 17.03

### 17.07.1 ###
- [x] update CriticalIO 2.0.01
- [x] update Sdvideo and add multiple version support 17.00 and 17.01

### 17.08.1 ###
- [x] update Sdvideo 17.02 (replace 17.01 - internpro has 17.00 and 17.02)
- [x] update SkyLynx firmware 1.18.0.0

### current ###
- [x] [devtoolset-6](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/) aka gcc 6.2.1 (ticket 8407)
- [x] we'll need cmake version 3.7.2 (required for boost 1.63.0) installed on development systems
### next ###
- [ ] CentOS 7 container, Docker
- [ ] turn clang-format SortIncludes on
- [ ] propose new palam libraries that take existing third-party library wrapper code (currently in Vantage) and build unit tests with good coverage and/or tests tools that give us confidence as we move to new versions of third-party libraries (for example: Sdimage/Codecs, Sdbase/Curl, Sdbase/Crypto, Sdbase/wxSDL and other wx-based code like Sdbase/HelpSys and Sdbase/Settings)

**Comment by smanders** [comment]
3.46 development is complete
