### ISSUE TITLE
priorities 3.48

### ISSUE THREAD

**Issue by smanders** [smanders/externpro#150]
### [17.10.1](https://github.com/smanders/externpro/milestone/13?closed=1)
- [x] [gSOAP download URL appears to be broken](https://github.com/smanders/externpro/issues/141)
- [x] [jxrlib tweaks](https://github.com/smanders/externpro/issues/143)
- [x] [remove libRaptorQ](https://github.com/smanders/externpro/issues/78)
- [x] [WebSocket++ build doesn't install headers on Windows](https://github.com/smanders/externpro/issues/145)
- [x] [upstream repos have changed for c-ares and curl](https://github.com/smanders/externpro/issues/146)
- [x] [LuaBridge no longer needs to be patched](https://github.com/smanders/externpro/issues/147)
- [x] [add ffmpegBin](https://github.com/smanders/externpro/issues/148)
- [x] [version libraries and includes](https://github.com/smanders/externpro/issues/142)
- [x] [Security update for nodejs](https://github.com/smanders/externpro/issues/144)
- [x] [download issues](https://github.com/smanders/externpro/issues/149)

### [18.01.1](https://github.com/smanders/externpro/milestone/14?closed=1)
- [x] [internal cmake enhancements](https://github.com/smanders/externpro/issues/151)
- [x] [projects with multiple downloads](https://github.com/smanders/externpro/issues/26)
- [x] [add OpenH264](https://github.com/smanders/externpro/issues/153)
- [x] [extract bz2](https://github.com/smanders/externpro/issues/152)
- [x] [enable FFmpeg to build with OpenH264](https://github.com/smanders/externpro/issues/154)
- [x] [update the cmake version](https://github.com/smanders/externpro/issues/156)
- [x] [add yasm](https://github.com/smanders/externpro/issues/157)
- [x] [add FFmpeg](https://github.com/smanders/externpro/issues/17)
- [x] [build OpenH264 with cmake](https://github.com/smanders/externpro/issues/155)
- [x] [extern environment variable and install directory](https://github.com/smanders/externpro/issues/158)
- [x] [remove node.js version 6.9.0](https://github.com/smanders/externpro/issues/159)
- [x] [gcc dumpversion](https://github.com/smanders/externpro/issues/160)

### 17.09.1
- [x] update Sdvideo 17.03 (replace 17.02 - internpro has 17.00 and 17.03)
- [x] update Sdvideo 17.04 (replace 17.03 - internpro has 17.00 and 17.04)

### 17.10.1
- [x] version libraries and includes
- [x] move ffmpeg to externpro
- [x] use latest release of externpro (17.10.1)
- [x] RDTP tweaks
- [x] remove GDP 17.04
- [x] update Sdvideo 17.05 and 17.06 (17.05 matches 17.04 but with ffmpeg in externpro)
- [x] palam built against node 6.11.4 (v115)

### 17.12.1
- [x] delete sol_dev branch
- [x] update palam v120 (replace v114 - internpro has v115 and v120)
- [x] update Sdvideo 17.07 (replace 17.05 - internpro has 17.06 and 17.07)

### 18.01.1
- [x] use latest release of externpro (18.01.1)
- [x] Sdvideo for Linux (18.01 - internpro has 17.07 and 18.01)
- [x] RDTP library for Linux (version 2.3)
- [x] update palam v121 (replace v120 - internpro has v115 and v121)

### 18.01.2
- [x] update palam v122 (replace v121 - internpro has v115 and v122)

### 18.02.1
- [x] remove Sdvideo 17.07
- [x] update palam v123 (replace v115 - internpro has v122 and v123)
- [x] remove .gitignore file
- [x] update CriticalIO 2.0.02
- [x] add SkyLynx CDLDriver
- [x] remove SkyLynx CDLDriver

### 18.03.1
- [x] update GDP 18.01 (replace version 17.05)
