### ISSUE TITLE
priorities 3.50

### ISSUE THREAD

**Issue by smanders** [smanders/externpro#176]
### [18.04.1](https://github.com/smanders/externpro/milestone/15?closed=1)
- [x] [projects/README.md PATCH](https://github.com/smanders/externpro/issues/162)
- [x] [ffmpeg and the troublesome lzma](https://github.com/smanders/externpro/issues/163)
- [x] [Generated cmake RPM won't install on CentOS 7](https://github.com/smanders/externpro/issues/164)
- [x] [add expat](https://github.com/smanders/externpro/issues/166)
- [x] [add libstrophe](https://github.com/smanders/externpro/issues/161)
- [x] [custom function for build step](https://github.com/smanders/externpro/issues/170)
- [x] [add cmake-built glew 1.13.0](https://github.com/smanders/externpro/issues/171) on linux
- [x] [enhance and fix xpPostBuildCopy](https://github.com/smanders/externpro/issues/86)
- [x] [download errors from sourceforge hosted downloads](https://github.com/smanders/externpro/issues/173)
- [x] [add Ceres Solver](https://github.com/smanders/externpro/issues/174)
- [x] [add node.js 8.11.0](https://github.com/smanders/externpro/issues/179)
- [x] [XP_CMAKE_REPO_INSYNC issues](https://github.com/smanders/externpro/issues/177)
- [x] [migrate cmake functions and macros](https://github.com/smanders/externpro/issues/180)
- [x] [xpTargetExtern as replacement for xpGetExtern](https://github.com/smanders/externpro/issues/182)

### [18.08.1](https://github.com/smanders/externpro/milestone/16?closed=1)
- [x] [Ceres Solver 1.14.0 doesn't build with gcc7](https://github.com/smanders/externpro/issues/186)
- [x] [geotrans data download error](https://github.com/smanders/externpro/issues/188)
- [X] [Visual Studio 2017 support](https://github.com/smanders/externpro/issues/185)
- [x] [remove node v6 and NPM support](https://github.com/smanders/externpro/issues/193)
- [x] [geotranz download error](https://github.com/smanders/externpro/issues/192)
- [x] [wxWidgets patch for tab traversal](https://github.com/smanders/externpro/issues/195)
- [x] [glew builds and use script](https://github.com/smanders/externpro/issues/199)
- [x] [use script cleanup](https://github.com/smanders/externpro/issues/169)
- [x] [remove add_definitions from use scripts](https://github.com/smanders/externpro/issues/183)
- [x] [wxcmakeover](https://github.com/smanders/externpro/issues/197)
- [x] [dependency graph](https://github.com/smanders/externpro/issues/200)
- [x] [add nuget](https://github.com/smanders/externpro/issues/201) (version 2.8.6)
- [x] [VS2017: clang-format-vs](https://github.com/smanders/externpro/issues/189)
- [x] [debug libraries](https://github.com/smanders/externpro/issues/132)
- [x] [INTERFACE_LINK_LIBRARIES in cmake-generated targets.cmake](https://github.com/smanders/externpro/issues/194)
- [x] [exclude several boost libraries from build](https://github.com/smanders/externpro/issues/202)
- [x] [boost 1.63.0 interprocess patch](https://github.com/smanders/externpro/issues/204)
- [x] [update the boost version](https://github.com/smanders/externpro/issues/198) (version 1.67.0)
- [x] [disable boost 1.63.0 Visual Studio 2017 build](https://github.com/smanders/externpro/issues/205)
- [x] [update the cmake version](https://github.com/smanders/externpro/issues/203) (version 3.12.0)

### [18.08.2](https://github.com/smanders/externpro/milestone/17?closed=1)
- [x] [gcc7 support](https://github.com/smanders/externpro/issues/191)
- [x] [ceres library in lib64 on CentOS](https://github.com/smanders/externpro/issues/206)
- [x] [need debug libraries for MSVC debug build](https://github.com/smanders/externpro/issues/207)

### [18.08.3](https://github.com/smanders/externpro/milestone/18?closed=1)
- [x] [cmake doesn't find boost 1.67 libraries](https://github.com/smanders/externpro/issues/208)

### 18.05.1
- [x] slurp shouldn't determine variable name 
- [x] rename skylynx project to sklynxlegacy 
- [x] add skylynx modernization firmware
- [x] add skylynx cdl card firmware
- [x] use latest release of externpro (18.04.1) - including internpro projects that can/should take advantage of externpro cmake enhancements
  - [x] slurp
  - [x] palam
  - [X] NG_GDP
  - [X] Sdvideo

### 18.08.1
- [x] remove node addon palam/mb/js NodeConnection (SLWeb NodeMbStreamer)
- [x] cmake error on CentOS from palam use script
- [x] two versions of projects that build against boost required
- [x] modifications needed to build against boost 1.67.0 and Visual Studio 2017
- [x] use script cleanup
- [x] use latest release of externpro (18.08.1 or later)
