### ISSUE TITLE
priorities 3.52

### ISSUE THREAD

**Issue by smanders** [smanders/externpro#209]
### [18.08.4](https://github.com/smanders/externpro/milestone/19?closed=1)
- [x] [wxwidgets use script issues](https://github.com/smanders/externpro/issues/210)
- [x] [bzip2 download error](https://github.com/smanders/externpro/issues/211)
- [x] [ffmpeg and troublesome link errors](https://github.com/smanders/externpro/issues/212)

### [18.11.1](https://github.com/smanders/externpro/milestone/20?closed=1)
- [x] [use cmake-provided MSVC_TOOLSET_VERSION](https://github.com/smanders/externpro/issues/213)
- [x] [merge modules relocated with Visual Studio 2017](https://github.com/smanders/externpro/issues/214)
- [x] [remove boost 1.63](https://github.com/smanders/externpro/issues/216)
- [x] [add CUB](https://github.com/smanders/externpro/issues/215)
- [x] [add node.js 8.12.0](https://github.com/smanders/externpro/issues/218)
- [x] [cmake AUTHOR_WARNING if linux distribution doesn't match](https://github.com/smanders/externpro/issues/220)
- [x] [~~update cmake from 3.12.0 to latest 3.12~~](https://github.com/smanders/externpro/issues/217)
- [x] [wxInclude is too verbose, needs quiet mode](https://github.com/smanders/externpro/issues/222)
- [x] [remove websocketpp](https://github.com/smanders/externpro/issues/223)
- [x] [add xpInstallPro cmake function](https://github.com/smanders/externpro/issues/224)
- [x] [ceres solver issues](https://github.com/smanders/externpro/issues/221)

### [18.09.1](https://isrhub.usurf.usu.edu/smanders/internpro/milestone/44?closed=1)
- [x] [remove sarcuda project](https://isrhub.usurf.usu.edu/smanders/internpro/issues/158)
- [x] [use latest release of externpro (18.08.4 or later)](https://isrhub.usurf.usu.edu/smanders/internpro/issues/159)
- [x] [developer-specified dist directory](https://isrhub.usurf.usu.edu/smanders/internpro/issues/160)
- [x] [new skylynx release](https://isrhub.usurf.usu.edu/smanders/internpro/issues/161)
- [x] [new skylynxcdlcard version scheme](https://isrhub.usurf.usu.edu/smanders/internpro/issues/162)

### [18.12.1](https://isrhub.usurf.usu.edu/smanders/internpro/milestone/45?closed=1)
- [x] [remove NRL project](https://isrhub.usurf.usu.edu/smanders/internpro/issues/165)
- [x] [palam v131](https://isrhub.usurf.usu.edu/smanders/internpro/issues/163)
- [x] [new skylynx release](https://isrhub.usurf.usu.edu/smanders/internpro/issues/167) (sl18.11.1)
- [x] [new skylynxcdlcard release](https://isrhub.usurf.usu.edu/smanders/internpro/issues/166) (cdl18.11.1)
- [x] [use latest release of externpro (later than 18.08.4)](https://isrhub.usurf.usu.edu/smanders/internpro/issues/164)
- [x] [add VantagePluginSDK](https://isrhub.usurf.usu.edu/smanders/internpro/issues/168)

### [19.01.1](https://isrhub.usurf.usu.edu/smanders/internpro/milestone/46?closed=1)
- [x] [pluginsdk enhancements 2.6.3.1](https://isrhub.usurf.usu.edu/smanders/internpro/issues/171)
- [x] [update palam URLs](https://isrhub.usurf.usu.edu/smanders/internpro/issues/172)
- [x] [palam v132](https://isrhub.usurf.usu.edu/smanders/internpro/issues/173)

### [19.02.1](https://isrhub.usurf.usu.edu/smanders/internpro/milestone/47?closed=1)
- [x] [pluginsdk enhancements](https://isrhub.usurf.usu.edu/smanders/internpro/issues/174) 2.6.3.3
- [x] [palam v140](https://isrhub.usurf.usu.edu/smanders/internpro/issues/175)

### [19.02.2](https://isrhub.usurf.usu.edu/smanders/internpro/milestone/48?closed=1)
- [x] [pluginsdk 2.6.4 release](https://isrhub.usurf.usu.edu/smanders/internpro/issues/176)
- [x] [documentation for XP_DEV cmake options](https://isrhub.usurf.usu.edu/smanders/internpro/issues/170)

### current
- [x] [cmake 3.12](https://isrhub.usurf.usu.edu/petemace/VantageSuper/pull/2909) deployment - needed for switch to boost 1.67 
- [x] [devtoolset-7](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/) aka gcc 7.3.1
- [x] sustained code
  - [x] [RIP](https://isrhub.usurf.usu.edu/petemace/VantageSuper/pull/2919)
  - [x] [Super](https://isrhub.usurf.usu.edu/Sustained/SustainedSuper/pull/1)
- [x] Visual Studio 2017 deployment
- [x] use cmake `GLOBAL_DEPENDS_NO_CYLES` global property (requires cmake > current 3.7.2)
  - from Seth Humphries: "I mentioned to you a while back that cmake now has a way to check for cyclic dependencies. It will fail at cmake time if such are present. I believe that for cmake 3.9.x the flag was introduced and on by default; in 3.10 the flag is present but off by default."
  - "If you are wanting to use that,  you can see where we turn the flag on here: https://isrhub.usurf.usu.edu/mdp/mdp/blob/develop/CMakeLists.txt#L28"
  - from Kenneth: "I suspect that we are free of such dependencies but if there is a cmake flag to help insure them it seems like a reasonable thing to add."
  - completed with commit https://isrhub.usurf.usu.edu/petemace/VantageShared/commit/4015f711ebf2ab2854f2830b4eee798857d3d338
- [x] install PluginSDK (externpro-like)
- [x] [cmakeup](https://isrtrac.usurf.usu.edu/trac/isr/ticket/10749)
- [x] `CRTool clean` keep developer comments in .codereview files
- [x] CopyrightChecker doesn't add copyright to .proto files - [list of extensions](https://isrhub.usurf.usu.edu/petemace/VantageTools/blob/development/CopyrightChecker/FileUtils.cpp#L45-L49)
- [x] turn clang-format SortIncludes on
- [x] ~~libgit2 slowness, ATT git-lfs investigation~~
- [x] plugin cmake and other common (.in) file consolidation
- [x] serialized builds when there are cpp files with the same name
  * from CMAKE_BINARY_DIR:
    * `find */*/*.dir/Release/*/ -type f -not -path *.tlog*` (Sdmidb)
    * `find */*/*/*.dir/Release/*/ -type f -not -path *.tlog*` (quite a bit)
    * `find */*/*/*/*.dir/Release/*/ -type f -not -path *.tlog*` (ATTLib, Test)
  * A.J. reported the build went ~ 2 min 45 sec faster!
### plugin_dev branches into development
https://isrhub.usurf.usu.edu/Vantage/VantageShared/branches/all
https://isrhub.usurf.usu.edu/Vantage/VantageShared/compare/development...smanders:Plugin_dev_merge
- [x] MosaicPlugin_dev
  https://isrhub.usurf.usu.edu/Vantage/VantageShared/compare/development...MosaicPlugin_dev
- [x] SICDPlugin_dev
  https://isrhub.usurf.usu.edu/Vantage/VantageShared/compare/development...SICDPlugin_dev
- [x] STANAG4607_dev
  https://isrhub.usurf.usu.edu/Vantage/VantageShared/compare/development...STANAG4607_dev
- [x] NITFCodecPlugin_dev
  https://isrhub.usurf.usu.edu/Vantage/VantageShared/compare/development...NITFCodecPlugin_dev
  Can't automatically merge
- [x] DFCPlugin_dev
  https://isrhub.usurf.usu.edu/Vantage/VantageShared/compare/development...DFCPlugin_dev
  1 commit, 0 files changed
- [x] FSGIPlugin_dev
  https://isrhub.usurf.usu.edu/Vantage/VantageShared/compare/development...FSGIPlugin_dev
  1 commit, 0 files changed

**Comment by smanders** [comment]
priorities 3.54 https://github.com/smanders/externpro/issues/228

**Comment by smanders** [comment]
reopen to track that Plugin_dev branches are merged into development before 3.52 release

**Comment by smanders** [comment]
all Plugin_dev branches are up-to-date with master (3.52 release) https://isrhub.usurf.usu.edu/Vantage/VantageShared/branches/all
