### ISSUE TITLE
priorities 3.54

### ISSUE THREAD

**Issue by smanders** [smanders/externpro#228]
### [19.06.1](https://github.com/smanders/externpro/milestone/21?closed=1)
- [x] [ffmpeg 2.6.2 build fails](https://github.com/smanders/externpro/issues/231)
- [x] [stop building clang-format VS extension](https://github.com/smanders/externpro/issues/227)
- [x] [utilize PROJECT_VERSION](https://github.com/smanders/externpro/issues/232)
- [x] [add .crtoolrc to miscFiles](https://github.com/smanders/externpro/issues/230)
- [x] [gcc debug optimizations](https://github.com/smanders/externpro/issues/234)
- [x] [dependency graph cmake-generated](https://github.com/smanders/externpro/issues/237)
- [x] [make coverage failures](https://github.com/smanders/externpro/issues/239)
- [x] [xpPostBuildCopy conditional copy_directory flaw](https://github.com/smanders/externpro/issues/238)
- [x] [add nasm](https://github.com/smanders/externpro/issues/240)
- [x] [add node.js 10.x and remove node.js 8.11.0](https://github.com/smanders/externpro/issues/219)
- [x] [cmake CXX_STANDARD](https://github.com/smanders/externpro/issues/235)
- [x] [multi-library project support](https://github.com/smanders/externpro/issues/236)

### [19.05.1](https://isrhub.usurf.usu.edu/smanders/internpro/milestone/49?closed=1)
- [x] [remove CibFirmware project](https://isrhub.usurf.usu.edu/smanders/internpro/issues/178)
- [x] [GDP 19.00](https://isrhub.usurf.usu.edu/smanders/internpro/issues/180)
- [x] [pluginsdk 2.9.1.4](https://isrhub.usurf.usu.edu/smanders/internpro/issues/181)
- [x] [kakadu 6.4](https://isrhub.usurf.usu.edu/smanders/internpro/issues/6)
- [x] [palam 1.4.2.0](https://isrhub.usurf.usu.edu/smanders/internpro/issues/177)

### [19.06.1](https://isrhub.usurf.usu.edu/smanders/internpro/milestone/50?closed=1)
- [x] [palam 1.4.4.0](https://isrhub.usurf.usu.edu/smanders/internpro/issues/183)
- [x] [use latest release of externpro](https://isrhub.usurf.usu.edu/smanders/internpro/issues/185)
- [x] [pluginsdk 2.9.1.9](https://isrhub.usurf.usu.edu/smanders/internpro/issues/184)
- [x] [remove GDP 18.06](https://isrhub.usurf.usu.edu/smanders/internpro/issues/186)

### [19.07.1](https://isrhub.usurf.usu.edu/smanders/internpro/milestone/51?closed=1)
- [x] [GDP 19.01](https://isrhub.usurf.usu.edu/smanders/internpro/issues/187)
- [x] [palam 1.4.5.0](https://isrhub.usurf.usu.edu/smanders/internpro/issues/188)
- [x] [pluginsdk 3.0.0.0](https://isrhub.usurf.usu.edu/smanders/internpro/issues/189)

### [19.09.1](https://isrhub.usurf.usu.edu/smanders/internpro/milestone/52?closed=1)
- [x] [remove pluginsdk 2.6.4.0 and ggdp 19.00](https://isrhub.usurf.usu.edu/smanders/internpro/issues/190)
- [x] [palam 1.4.6.0](https://isrhub.usurf.usu.edu/smanders/internpro/issues/191)
- [x] [pluginsdk 3.0.1.0](https://isrhub.usurf.usu.edu/smanders/internpro/issues/192)

### [19.10.1](https://isrhub.usurf.usu.edu/smanders/internpro/milestone/53?closed=1)
- [x] [remove pluginsdk 3.0.0.0 and palam 1.4.5.0](https://isrhub.usurf.usu.edu/smanders/internpro/issues/194)
- [x] [pluginsdk 3.0.2.0](https://isrhub.usurf.usu.edu/smanders/internpro/issues/196)
- [x] [palam 1.5.0.0](https://isrhub.usurf.usu.edu/smanders/internpro/issues/193)

### current
- [x] Plugin SDK support https://isrhub.usurf.usu.edu/orgs/VantagePlugins/projects/1
- [x] fix include of extern headers in lib headers
  - [x] Sdrest cURL
    * CRTool, CRToolCommon, CRToolCommon/Test, RestTool, UnicornService, UnicornService/Test, ATTLib, ATTPlans, Sdrest/Test
  - [x] Sdbase lua
    * PluginTestEmulator-gui, Sdbase/Test, Sdbase/Scripting/TestTool
  - [x] Sdimage shapelib
    * ProcessSensor
  - [x] Sdimage eigen (3.56 xpro::eigen changes)
    * Sdvis, FSP
  - [x] DataFlowService eigen (3.56 xpro::eigen changes)
    * DataFlowService/Test

**Comment by smanders** [comment]
priorities 3.56 https://github.com/smanders/externpro/issues/263
