### ISSUE TITLE
priorities 3.42

### ISSUE THREAD

**Issue by smanders** [smanders/externpro#72]
16.04.1
- [x] [Node.js](https://github.com/smanders/externpro/issues/69)
- [x] Visual Studio 2015
- [x] palam (internpro)

16.06.1
- [x] [wxWidgets](https://github.com/smanders/externpro/issues/67)
- [x] palam (internpro)

16.07.1
- [x] [update README with usage details](https://github.com/smanders/externpro/issues/95)
- [x] [remove vld](https://github.com/smanders/externpro/issues/70) Visual Studio 2015 support
- [x] [remove wxWidgets 3.0.2](https://github.com/smanders/externpro/issues/96)
- [x] [remove Node.js v0 and Solaris support](https://github.com/smanders/externpro/issues/90)
- [x] [make 64-bit detection more robust](https://github.com/smanders/externpro/issues/97)

16.09.1
- [x] [wxGTK 3.1.0 wxDataViewCustomRenderer issues](https://github.com/smanders/externpro/issues/106)
- [x] [enhance xpSourceListAppend](https://github.com/smanders/externpro/issues/101)

current
- [ ] Windows 10, Server 2012

next
- [ ] [boost](https://github.com/smanders/externpro/issues/39)
- [ ] [FFmpeg](https://github.com/smanders/externpro/issues/17)
- [ ] [libRaptorQ shared libs](https://github.com/smanders/externpro/issues/71)
- [ ] [glew](https://github.com/smanders/externpro/issues/18)
- [ ] [openssl link errors](https://github.com/smanders/externpro/issues/48)

**Comment by smanders** [comment]
3.42 development is complete
